### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by uduse** [Uduse/Sublime-GameMaker-Studio-Language-Bundle#1]
There are a bunch of missing functions in the bundle. Gamepad functions are completely missing. Audio functions miss snippets.

The reason is that I couldn't find a reliable source of a list of all functions with their signature. I tried to parse the manual both locally and via the web version, but all failed. 

Solutions:
- wait for an official release of documentation in other forms (see [my request on official forum here](http://help.yoyogames.com/hc/en-us/community/posts/115000791447-is-there-documentation-in-other-forms-))
- someone help me to parse the manual
- someone transfer those functions manually (just function names and signature is enough, see gml-functions.txt, and my Python script will do the rest)

**Comment by Trebor777** [comment]
You can check in the install folder of GMS, there are text files containing all the functions, macros, variables etc...
<install_path>\GameMaker Studio 2\TextEditor

**Comment by uduse** [comment]
@Trebor777 yeah I found that as well (after writing an online document crawler 😢 ) in fact, I am preparing for the next big update to replace everything with GMS 2 stuff
