### ISSUE TITLE
Can I convert Syntax and add it to the VSCode plugin?

### ISSUE THREAD

**Issue by LiarOnce** [Uduse/Sublime-GameMaker-Studio-Language-Bundle#3]
This is my plugin's repository : [LiarOnce/gml-support](https://github.com/LiarOnce/gml-support)
I do this whether the infringement?
Thanks!

**Comment by uduse** [comment]
Sorry, didn't see your comment here. I just added a license, so you may use it freely.

**Comment by LiarOnce** [comment]
Thanks!
